Extensive fixes to ensure robust operation. Including: In derive_parameters: Control column force derived parameter added. In cases where runway has no ILS, the end of the runway is taken as the reference point.
In flight_phase.py:
During approach and go-around the approach kpvs used for identifying the approach runway (not landing kpvs).
Aircraft location used to identify takeoff runway when using parallel runways.
Logic for airborne phase revised to make condition more robust, expecially in presence of corrupt data.
Phase DescentLowClimb amended to correctly reflect descent prior to climb, in the absence of a radio altitude signal above 2500ft.
Fast amended to operate on progressive change through AIRSPEED_THRESHOLD and ignore spike transitions. Also periods too short to constitute a flight now ignored.
Array overrun in final_approach corrected.
ILS scanning correction applied to ignore rapid transitions through the glideslope beam (although further improvement planned).

In key_point_values.py:
ControlColumnStiffness added
Go-around minimum altitude now correctly identified.
HeadingAtLanding, HeadingAtTakeoff amended to take median across complete phase (peak acceleration instant not reliable as this often happened at the end of the takeoff or landing roll).
ILS Frequency on Approach part amended to add left and right frequencies, but better solution with data masked when mismatched made this unnecessary.

In library.py:
coreg - trap added for invariant independant parameter (seen once in stick force data)
hysteresis altered to correct error with masked data (mask was reflected in data during first pass)
repair_duration trap for small segments altered - needs better design as this is used in differing contexts from various routines.
slice_samples - trap for None slices

In flight_phase_test.py:
loc_established test for masked values added

In library_test.py:
Hysteresis test now checks for mask propagation correctly.
slice_samples test for None elements.
subslice test added using data from a flight -> still fails on this case.py

In process_flight_test.py:
Extensive changes to map data to files that can be run locally. Being replaced by other bulk replay facilities.

plot_flight, process_flight, settings.py, split_hdf_to_segments.py - Minor updates only.
-------------------------------------------------------------------------------------------------------
Note: Still fails too often with "AttributeError: 'TakeoffRunway' object has no attribute 'value'"